module.exports = [
  "basketball shoes",
  "boots",
  "casual shoes",
  "clogs",
  "cowboy boots",
  "dress shoes",
  "golf shoes",
  "high heel shoes",
  "loafers",
  "moccasins",
  "pumps",
  "rubber boots",
  "sandals",
  "shoes",
  "slippers",
  "sneakers",
  "spike shoes",
  "spikes",
  "steel toed shoes",
  "T-strap shoes",
  "tennis shoes",
  "thongs",
  "training shoes",
  "work boots"
];
